#
# Copyright (c) 2024, Proxeet Systems. All Rights Reserved.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Cable diagnostics LuCI interface
LUCI_DEPENDS:=+luci-base
LUCI_DESCRIPTION:=Some tools for cable diagnostics

PKG_MAINTAINER:= Evgeniy Tsybra <zcjack81@gmail.com>
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature