#!/bin/sh /etc/rc.common
#
# PoE Daemon Init Script
#
# Copyright (C) 2024 Proxeet Ltd.
# Author: Aleksei Vasilenko <a.vasilenko@proxeet.com>
#

USE_PROCD=1
START=19
STOP=10
SNAME=poed
PROG=/usr/bin/$SNAME

start_service() {
    echo "Start poe daemon..."
    procd_open_instance
    procd_set_param command "$PROG" -t
 #   procd_set_param file /etc/config/poed
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "$SNAME"
}

reload_service() {
    echo "Reloading poe daemon..."
    stop
    start
}

